apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-file
  namespace: {{ .Values.nameSpace }}
data:
  config.toml: |
    [network.client]
    server_address = "api.minikube.rds"

    [integration]
    scheme = "host"

    [integration.host]
    api_url = "http://{{HOST}}:8080/apps/rdsng/api/v1" # replace HOST

    [authorization.oauth2.client]
    id = ""
    redirect_url = "http://{{HOST}}:8080/apps/rdsng/main" # replace HOST