appName: "rds"

tag: "latest"

ingress:
  enabled: true
  hostname: "" # The server adress
  path: /
  tls:
  - hosts:
    - # The tls host adresses
    secretName:                                         # Holds  the certificate for the server, e.g. sciebords-server-tls
     
  annotations: {}

### Server
server:
  componentName: "server"
  address: ""                                           # The server adress
  image:
    name: "ghcr.io/sciebo-rds/rds-ng-server"
    pullPolicy: "Always"
  allowedOrigins: '"*"'
  databaseEngine: "sqlite"                              # sqlite | mariadb
  sqliteFile: "/data/rds.db"
  oauth2:                                               # oauth2 credentials configured within the hostsystem
    clientId: ""
    clientRedirectUrl: ""
    hostSecret: ""                                      
  networkApiKey: ""                                     # An arbitrary API key to access protected resources; this must be the same value on all components.


### Frontend
frontend:
  componentName: "frontend"
  integration:
    scheme: "host"
    hostApiUrl: ""                                      # The full URL where the host integration exposes its API; this needs to be in the form of <APP_URL>/api/v1 (e.g., http://localhost:8080/apps/rdsng/api/v1 for a local Nextcloud setup).
    clientId: ""                                        # The OAUTH2 client ID of the frontend.
  image:
    name: "ghcr.io/sciebo-rds/rds-ng-frontend"
    pullPolicy: "Always"
  ingress:
    enabled: true
    hostname: ""                                        # The frontend hostname           
    path: /
    tls:
    - hosts:
      - 
      secretName:                                       # Holds  the certificate for the server, e.g. sciebords-server-tls
       
    annotations: {}

###
### Connectors
###
connectors:

  ### OSF
  osf:
    enabled: true
    componentName: "connector-osf"
    image:
      name: "ghcr.io/sciebo-rds/rds-ng-connector-osf"
      pullPolicy: "Always"
    oauth2:
      clientId: ""                                      # The ClientID of your OSF oauth2 application
      clientSecret: ""                                  # The clientSecret of your OSF oauth2 application
  
  ### Zenodo
  zenodo:
    enabled: true
    componentName: "connector-zenodo"
    image:
      name: "ghcr.io/sciebo-rds/rds-ng-connector-zenodo"
      pullPolicy: "Always"
    oauth2:
      clientId: ""                                      # The ClientID of your Zenodo oauth2 application
      clientSecret: ""                                  # The clientSecret of your Zenodo oauth2 application

  ### Stub
  stub:
    enabled: true
    componentName: "connector-stub"
    image:
      name: "ghcr.io/sciebo-rds/rds-ng-connector-stub"
      pullPolicy: "Always"
    oauth2:
      clientId: ""                                      # A dummy ClientID
      clientSecret: ""                                  # A dummy clientSecret

