apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  RDS_NETWORK_SERVER_ALLOWED_ORIGINS: {{ .Values.server.allowedOrigins }}
  RDS_NETWORK_API_KEY: {{ .Values.server.networkApiKey }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_HOST: {{ .Values.server.oauth2.hostSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_OSF: {{ .Values.connectors.osf.oauth2.clientSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_ZENODO:  {{ .Values.connectors.zenodo.oauth2.clientSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_STUB:  {{ .Values.connectors.stub.oauth2.clientSecret }}
  RDS_STORAGE_DATABASE_driver: {{ .Values.server.storage.driver }}
  RDS_STORAGE_DATABASE_ENGINE: {{ .Values.server.storage.databaseEngine }}

  {{- if eq .Values.server.storage.databaseEngine "sqlite" -}}
  RDS_STORAGE_DATABASE_SQLITE_FILE: {{ .Values.server.sqlite.sqliteFile }}
  {{ - end }}

  {{- if eq .Values.server.storage.databaseEngine "postgresql" -}}
  RDS_STORAGE_DATABASE_POSTGRESQL_HOST: {{ .Values.server.postgresql.host }}
  RDS_STORAGE_DATABASE_POSTGRESQL_PORT: {{ .Values.server.postgresql.port }}
  RDS_STORAGE_DATABASE_POSTGRESQL_DATABASE: {{ .Values.server.postgresql.database }}
  RDS_STORAGE_DATABASE_POSTGRESQL_USER: {{ .Values.server.postgresql.user }}
  RDS_STORAGE_DATABASE_POSTGRESQL_PASSWORD: {{ .Values.server.postgresql.password }}
  {{ - end }}

  {{- if eq .Values.server.storage.databaseEngine "mysql" -}}
  RDS_STORAGE_DATABASE_MYSQL_HOST: {{ .Values.server.mysql.host }}
  RDS_STORAGE_DATABASE_MYSQL_PORT: {{ .Values.server.mysql.port }}
  RDS_STORAGE_DATABASE_MYSQL_DATABASE: {{ .Values.server.mysql.database }}
  RDS_STORAGE_DATABASE_MYSQL_USER: {{ .Values.server.mysql.user }}
  RDS_STORAGE_DATABASE_MYSQL_PASSWORD: {{ .Values.server.mysql.password }}
  {{ - end }}

  {{- if eq .Values.server.storage.databaseEngine "mariadb" -}}
  RDS_STORAGE_DATABASE_MARIADB_HOST: {{ .Values.server.mariadb.host }}
  RDS_STORAGE_DATABASE_MARIADB_PORT: {{ .Values.server.mariadb.port }}
  RDS_STORAGE_DATABASE_MARIADB_DATABASE: {{ .Values.server.mariadb.database }}
  RDS_STORAGE_DATABASE_MARIADB_USER: {{ .Values.server.mariadb.user }}
  RDS_STORAGE_DATABASE_MARIADB_PASSWORD: {{ .Values.server.mariadb.password }}
  {{ - end }}