apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  RDS_AUTHORIZATION_OAUTH2_SECRETS_HOST: {{ .Values.server.secrets.host }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_OSF: {{ .Values.server.secrets.osf }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_ZENODO: {{ .Values.server.secrets.zenodo }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_STUB: {{ .Values.server.stub }}
  RDS_NETWORK_API_KEY: {{ .Values.server.secrets.networkApiKey }}
