name: Build and publish a container image for the 'develop' branch
on:
    push:
        branches: [ 'develop' ]
        tags:
            - develop
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Build containers
                run: cd deployment/containers && make dev-build
            -   name: Log in to registry
                run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            -   name: Push server image
                run: |
                    IMAGE_ID=ghcr.io/${{ github.repository_owner }}/rds-ng-server
                    VERSION=develop
                    
                    echo IMAGE_ID=$IMAGE_ID
                    echo VERSION=$VERSION
                    docker tag docker.io/rds-ng/server:develop $IMAGE_ID:$VERSION
                    docker push $IMAGE_ID:$VERSION
